### ISSUE TITLE
update for 2025?

### ISSUE THREAD

**Issue by r2evans** [wfrierson/wmm#4]
The current `.DeriveVersionInfo` errors because we're into 2025. Is there a clear (and preferably "easy") path to update this package for current year?

**Comment by r2evans** [comment]
I see that this needs the `WMM2025.csv` file, which I'm assuming can be derived from the `WMM2025COF.zip` file from the WMM's download page. I started going through the `inst/creatingSysData.R` file, but I don't have the past `.csv` files. (I'm also confused by `fread(..., sep="|")`, since the files I see in the 2025COF zip are fixed-with tables or similar, not `|`-delimited. Must be something to do with the `.COF` file extension.)

If there's a different source for the data other than https://www.ncei.noaa.gov/products/world-magnetic-model, I can look there. This is all in the interest of trying to help.

**Comment by wfrierson** [comment]
Thanks for the feedback, @r2evans. I'm on family leave until later this month. When I return, I'll update the repo with the 2025 coefficients. Later in the Spring, I'll update the CRAN package.

Thanks for your patience!

**Comment by wfrierson** [comment]
Update: ~I've tried downloading the coefficient file 3 times now through NOAA, but it never begins. I'll try contacting someone there.~

After some sleuthing, I found a copy. I'll update the GitHub page next week, barring any other issues.

**Comment by Rafnuss** [comment]
Just to make sure I'm not missing anything, the 2025 is still not implemented, right?
Would be nice to be able to generate the csv table from the COF file! Is that feasiable? Happy to help!

**Comment by wfrierson** [comment]
**Update**: On my machine, I've updated `R/sysdata.rda` with the latest coefficients. I need to clean up the documentation, push commits, and merge with main.

Thank you for everyone's patience!

**Comment by wfrierson** [comment]
**Update**: I've merged the PR into main.

Note: Although this repo is now up-to-date with WMM, I need more time to update the CRAN package.
